#!/system/bin/sh
# Create the directory if it doesn't exist
#mkdir -p /data/adb/VerifiedBootHash

# Try getting vbmeta digest from system properties
#boot_hash=$(getprop ro.boot.vbmeta.digest)

# If not found, compute SHA-256 hash of vbmeta partition
#if [ -z "$boot_hash" ] && [ -e /dev/block/by-name/vbmeta ]; then
#    boot_hash=$(dd if=/dev/block/by-name/vbmeta bs=4k count=1 2>/dev/null | sha256sum | awk '{print $1}')
#fi

# Save the boot hash
#echo "# BOOT HASH GENERATED BY Integrity-Box" > /data/adb/VerifiedBootHash/VerifiedBootHash.txt
#echo "# Updated on $(date '+%A %d/%m/%Y %I:%M:%S%p')" >> /data/adb/VerifiedBootHash/VerifiedBootHash.txt
#echo "#" >> /data/adb/VerifiedBootHash/VerifiedBootHash.txt
#echo "$boot_hash" >> /data/adb/VerifiedBootHash/VerifiedBootHash.txt
  
# Remove the package cache & directory.
rm -rf /data/system/package_cache

# Remove unnecessary modules
# You don't need them, Integrity-Box covers everything alone.
rm -rf /data/adb/modules/Ttarget
rm -rf /data/adb/modules/FBE_Enabler
rm -rf /data/adb/modules/HideMyRoot
rm -rf /data/adb/modules/Camouflaged_data_encryption
#rm -rf /data/adb/modules/Integrity-Box/disable

# Define paths
SRC="/data/adb/modules/Integrity-Box/sus.sh"
DEST_DIR="/data/adb/modules/susfs4ksu"
DEST_FILE="$DEST_DIR/action.sh"

# Check if the destination directory exists
if [ ! -d "$DEST_DIR" ]; then
    echo "❌ Directory not found: $DEST_DIR. Exiting..."
    exit 1
fi

# Copy Copy 
cp "$SRC" "$DEST_FILE"

# Set perms
chmod +x "$DEST_FILE" 
chmod 644 "$DEST_FILE" 

# Auto enable 
DISABLE_FILE="/data/adb/modules/Integrity-Box/disable"
[ -f "$DISABLE_FILE" ] && rm -f "$DISABLE_FILE"