name: Build & Release Magisk Module

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get previous tags

    - name: Determine next release version
      id: get_tag
      run: |
        latest_tag=$(git tag --sort=-creatordate | grep -E '^[0-9]+\.[0-9]+$' | head -n 1)
        if [ -z "$latest_tag" ]; then
          new_tag="1.00"
        else
          new_tag=$(awk -F. '{printf "%.2f", $1 + ($2 + 5)/100}' <<< "$latest_tag")
        fi
        echo "next=$new_tag" >> $GITHUB_OUTPUT

    - name: Set module ZIP name
      run: echo "MODULE_ZIP=Integrity-Box-${{ steps.get_tag.outputs.next }}.zip" >> $GITHUB_ENV

    - name: Zip the module
      run: |
        zip -r "$MODULE_ZIP" . -x ".git/*" ".github/*" "*.zip"

    - name: Create and push git tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag -a "${{ steps.get_tag.outputs.next }}" -m "Release ${{ steps.get_tag.outputs.next }}"
        git push origin "${{ steps.get_tag.outputs.next }}"

    - name: Create GitHub release and attach ZIP
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_tag.outputs.next }}
        name: Release ${{ steps.get_tag.outputs.next }}
        files: ${{ env.MODULE_ZIP }}
